# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :'master' => {
         :box_name => "centos/7",
         :ip_addr => '192.168.11.10',
         :hostname => "web"
  },
  :'node' => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.11',
        :hostname => "log"
  }
}

Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|
        config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.hostname = boxconfig[:hostname]
          box.vm.network "private_network", ip: boxconfig[:ip_addr]
          box.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "1024"]
          end
          box.vm.provision "ansible" do |ansible|
            ansible.become = true
            ansible.playbook = "provision_logging.yml"
          end
      end
  end
end